### ISSUE TITLE
Wow, I didn't see that coming.

### ISSUE THREAD

**Issue by mundschenk-at** [dmester/jdenticon-php#1]
Hi @dmester! I just stumbled on your new repository, after I spent the last two days [porting jdenticon to PHP](https://github.com/mundschenk-at/avatar-privacy/commit/c64fd2f44f2306de5449436308e984094c26911b) (well, actually only the SVG part). Most bugs seem to be fixed now, except that I can't exactly reproduce the test SVG. 

Well, it was an interesting exercise, even if I ultimately get to switch to an official version. Thanks for your great work.

**Comment by dmester** [comment]
Hi! Too bad I didn't publish the PHP port a week earlier :-)

If you decide to switch to this PHP port, please note that it should still be considered a preview version as I haven't tested it in all supported PHP versions yet. I just realised I never marked the release as a pre-release, but now it is.

**Comment by mundschenk-at** [comment]
Yes, I already [switched to the new port](https://github.com/mundschenk-at/avatar-privacy/blob/master/includes/avatar-privacy/default-icons/generator/class-jdenticon.php) - not having to maintain the library myself is way easier. My WordPress plugin is written for PHP >= 5.6, so anything affecting earlier versions does not concern me. (Also, I tend to assume SemVer, so 0.9 was clearly a pre-release for me.)

**Comment by dmester** [comment]
Closing this issue. Please open a new issue if you encounter any issues using Jdenticon for PHP.
